#! /bin/sh

MONITOR1="DP-4"
MONITOR2="DP-2"

MONITOR=$MONITOR1 polybar -r spaces &
MONITOR=$MONITOR1 polybar -r window &
MONITOR=$MONITOR1 polybar -r stats &
MONITOR=$MONITOR2 polybar -r spaces-additional &
MONITOR=$MONITOR2 polybar -r music &

bspc monitor $MONITOR1 -d I II III IV V
bspc monitor $MONITOR2 -d VI VII VIII IX
#bspc monitor HDMI-0 -d X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true

bspc rule -a news desktop=^3
bspc rule -a Claws-mail desktop=^3
bspc rule -a discord desktop=^6
bspc rule -a chat desktop=^6

xset -b
sxhkd &
redshift &
$BROWSER &
sleep 4 && nextcloud &
discord &
claws-mail &

betterlockscreen -u /home/tim/files/current_wallpaper/wallhaven-156235.jpg &
$HOME/.fehbg

kitty --class news /usr/bin/newsboat &
kitty --class chat /usr/bin/weechat &
